# Generated by Django 5.1.4 on 2025-01-28 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_alter_news_options_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='category',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaranma tarİxİ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenİlənmə tarİxİ'),
        ),
    ]
